'use strict';

/**
 * GAME CONFIGURATION — Central source of truth for all game balance parameters.
 * All values here can be overridden via the game_config table in the database.
 * Changes to this file do NOT require code changes in business logic.
 */

const gameConfig = {
  // ─── EXPEDITION ────────────────────────────────────────────────────────────
  expedition: {
    baseDurationMinutes: 10,
    speedUpCostStars: 1,
    maxActivePerUser: 1,
  },

  // ─── STARS (Telegram Stars in-game wallet) ─────────────────────────────────
  stars: {
    topupAmounts: [10, 50, 100, 250, 500, 1000], // allowed topup denominations
    speedupCost: 1,                           // stars per expedition speedup
  },

  // ─── RARITY SYSTEM ─────────────────────────────────────────────────────────
  rarity: {
    common:    { weight: 72.0, xpMultiplier: 1.0,  priceMultiplier: 1.0,  label: 'Обычный' },
    rare:      { weight: 23.0, xpMultiplier: 1.8,  priceMultiplier: 2.0,  label: 'Редкий' },
    epic:      { weight: 4.2,  xpMultiplier: 3.5,  priceMultiplier: 4.0,  label: 'Эпический' },
    legendary: { weight: 0.7,  xpMultiplier: 8.0,  priceMultiplier: 8.0,  label: 'Легендарный' },
    mythical:  { weight: 0.1,  xpMultiplier: 18.0, priceMultiplier: 20.0, label: 'Мифический' },
  },

  // ─── FIND TYPE WEIGHTS (base, before zone modifiers) ───────────────────────
  findTypes: {
    asteroid: { weight: 15, label: 'Астероид' },
    debris:   { weight: 40, label: 'Космический мусор' },
    artifact: { weight: 20, label: 'Артефакт' },
    creature: { weight: 15, label: 'Существо' },
    anomaly:  { weight: 10, label: 'Аномалия' },
  },

  // ─── ZONES ─────────────────────────────────────────────────────────────────
  zones: [
    {
      id: 'galaxy_outskirts',
      name: 'Окраина галактики',
      minLevel: 1,
      rarityMultiplier: 1.0,
      findTypeModifiers: {
        debris: 1.5,
        asteroid: 1.2,
        creature: 0.8,
        anomaly: 0.5,
      },
      creditMultiplier: 1.0,
      xpMultiplier: 1.0,
    },
    {
      id: 'asteroid_field',
      name: 'Астероидное поле',
      minLevel: 5,
      rarityMultiplier: 1.15,
      findTypeModifiers: {
        asteroid: 2.5,
        debris: 1.2,
        creature: 0.6,
        anomaly: 0.7,
      },
      creditMultiplier: 1.1,
      xpMultiplier: 1.1,
    },
    {
      id: 'abandoned_sector',
      name: 'Заброшенный сектор',
      minLevel: 10,
      rarityMultiplier: 1.3,
      findTypeModifiers: {
        debris: 1.8,
        artifact: 1.5,
        creature: 1.2,
        anomaly: 1.0,
      },
      creditMultiplier: 1.25,
      xpMultiplier: 1.2,
    },
    {
      id: 'ancient_region',
      name: 'Древняя область',
      minLevel: 15,
      rarityMultiplier: 1.5,
      findTypeModifiers: {
        artifact: 2.5,
        anomaly: 1.5,
        creature: 1.3,
        debris: 0.8,
      },
      creditMultiplier: 1.5,
      xpMultiplier: 1.4,
    },
    {
      id: 'anomalous_zone',
      name: 'Аномальная зона',
      minLevel: 20,
      rarityMultiplier: 1.8,
      findTypeModifiers: {
        anomaly: 3.0,
        artifact: 1.8,
        creature: 1.5,
        debris: 0.7,
        asteroid: 0.8,
      },
      creditMultiplier: 1.8,
      xpMultiplier: 1.7,
    },
  ],

  // ─── GALAXY SECTORS ────────────────────────────────────────────────────────
  sectors: ['ARS', 'VEG', 'PER', 'ORN', 'CYG', 'TXN', 'NXD', 'KRP'],

  // ─── XP SYSTEM ─────────────────────────────────────────────────────────────
  xp: {
    baseExpeditionXP: 10,
    sellXPMultiplier: 0.5,    // XP from selling = baseXP * 0.5
    collectXPMultiplier: 1.0, // XP from collecting
    levelTable: [
      { level: 1,  xpRequired: 0 },
      { level: 2,  xpRequired: 200 },
      { level: 3,  xpRequired: 500 },
      { level: 4,  xpRequired: 900 },
      { level: 5,  xpRequired: 1500 },   // unlocks asteroid_field
      { level: 6,  xpRequired: 2300 },
      { level: 7,  xpRequired: 3300 },
      { level: 8,  xpRequired: 4600 },
      { level: 9,  xpRequired: 6200 },
      { level: 10, xpRequired: 8200 },   // unlocks abandoned_sector
      { level: 11, xpRequired: 10700 },
      { level: 12, xpRequired: 13700 },
      { level: 13, xpRequired: 17200 },
      { level: 14, xpRequired: 21200 },
      { level: 15, xpRequired: 26200 },  // unlocks ancient_region
      { level: 16, xpRequired: 32200 },
      { level: 17, xpRequired: 39200 },
      { level: 18, xpRequired: 47200 },
      { level: 19, xpRequired: 56200 },
      { level: 20, xpRequired: 66200 },  // unlocks anomalous_zone
      { level: 21, xpRequired: 78200 },
      { level: 22, xpRequired: 92200 },
      { level: 23, xpRequired: 108200 },
      { level: 24, xpRequired: 126200 },
      { level: 25, xpRequired: 148200 },
      { level: 26, xpRequired: 174200 },
      { level: 27, xpRequired: 204200 },
      { level: 28, xpRequired: 240200 },
      { level: 29, xpRequired: 282200 },
      { level: 30, xpRequired: 332200 },
      { level: 31, xpRequired: 390200 },
      { level: 32, xpRequired: 458200 },
      { level: 33, xpRequired: 536200 },
      { level: 34, xpRequired: 626200 },
      { level: 35, xpRequired: 728200 },
      { level: 36, xpRequired: 844200 },
      { level: 37, xpRequired: 974200 },
      { level: 38, xpRequired: 1120200 },
      { level: 39, xpRequired: 1282200 },
      { level: 40, xpRequired: 1462200 },
    ],
  },

  // ─── SHIP MODULES ──────────────────────────────────────────────────────────
  modules: {
    scanner: {
      label: 'Сканер',
      maxLevel: 10,
      // scansUpTo: max rarity index scannable (0=none, 1=common, 2=rare, 3=epic, 4=legendary, 5=mythical, 6+=U2 rarities)
      levels: [
        { level: 0,  rarityMultiplier: 1.0,  scansUpTo: 0, upgradeCost: 0 },
        { level: 1,  rarityMultiplier: 1.05, scansUpTo: 1, upgradeCost: 250 },
        { level: 2,  rarityMultiplier: 1.12, scansUpTo: 2, upgradeCost: 700 },
        { level: 3,  rarityMultiplier: 1.20, scansUpTo: 3, upgradeCost: 2500 },
        { level: 4,  rarityMultiplier: 1.30, scansUpTo: 4, upgradeCost: 7000 },
        { level: 5,  rarityMultiplier: 1.45, scansUpTo: 5, upgradeCost: 20000 },
        // Levels 6-10: crystal costs (costCrystals), handle U2 rarities
        { level: 6,  rarityMultiplier: 1.55, scansUpTo: 6, upgradeCost: 0, costCrystals: 500 },
        { level: 7,  rarityMultiplier: 1.60, scansUpTo: 7, upgradeCost: 0, costCrystals: 1500 },
        { level: 8,  rarityMultiplier: 1.65, scansUpTo: 8, upgradeCost: 0, costCrystals: 4000 },
        { level: 9,  rarityMultiplier: 1.70, scansUpTo: 9, upgradeCost: 0, costCrystals: 10000 },
        { level: 10, rarityMultiplier: 1.75, scansUpTo: 10, upgradeCost: 0, costCrystals: 25000 },
      ],
    },
    engine: {
      // Hidden from upgrade UI — reserved for future use
      hidden: true,
      label: 'Двигатель',
      maxLevel: 5,
      levels: [
        { level: 0, durationMultiplier: 1.0,  upgradeCost: 0 },
        { level: 1, durationMultiplier: 0.9,  upgradeCost: 350 },
        { level: 2, durationMultiplier: 0.8,  upgradeCost: 900 },
        { level: 3, durationMultiplier: 0.65, upgradeCost: 3200 },
        { level: 4, durationMultiplier: 0.5,  upgradeCost: 9000 },
        { level: 5, durationMultiplier: 0.35, upgradeCost: 24000 },
      ],
    },
    cargo: {
      label: 'Грузовой отсек',
      maxLevel: 10,
      // maxVolume: max item volume (м³) that fits in the hold
      levels: [
        { level: 0,  maxVolume: 35,  upgradeCost: 0 },
        { level: 1,  maxVolume: 45,  upgradeCost: 200 },
        { level: 2,  maxVolume: 65,  upgradeCost: 500 },
        { level: 3,  maxVolume: 90,  upgradeCost: 1800 },
        { level: 4,  maxVolume: 115, upgradeCost: 5000 },
        { level: 5,  maxVolume: 140, upgradeCost: 14000 },
        { level: 6,  maxVolume: 170, upgradeCost: 0, costCrystals: 400 },
        { level: 7,  maxVolume: 210, upgradeCost: 0, costCrystals: 1200 },
        { level: 8,  maxVolume: 260, upgradeCost: 0, costCrystals: 3500 },
        { level: 9,  maxVolume: 320, upgradeCost: 0, costCrystals: 8000 },
        { level: 10, maxVolume: 400, upgradeCost: 0, costCrystals: 20000 },
      ],
    },
    capsule: {
      label: 'Капсула для существ',
      maxLevel: 10,
      // capturesUpTo: max rarity index capturable (0=none, 1=common, ..., 5=mythical, 6+=U2)
      levels: [
        { level: 0,  capturesUpTo: 0, upgradeCost: 0 },
        { level: 1,  capturesUpTo: 1, upgradeCost: 300 },
        { level: 2,  capturesUpTo: 2, upgradeCost: 800 },
        { level: 3,  capturesUpTo: 3, upgradeCost: 2800 },
        { level: 4,  capturesUpTo: 4, upgradeCost: 8000 },
        { level: 5,  capturesUpTo: 5, upgradeCost: 22000 },
        { level: 6,  capturesUpTo: 6, upgradeCost: 0, costCrystals: 600 },
        { level: 7,  capturesUpTo: 7, upgradeCost: 0, costCrystals: 1800 },
        { level: 8,  capturesUpTo: 8, upgradeCost: 0, costCrystals: 5000 },
        { level: 9,  capturesUpTo: 9, upgradeCost: 0, costCrystals: 12000 },
        { level: 10, capturesUpTo: 10, upgradeCost: 0, costCrystals: 30000 },
      ],
    },
  },

  // ─── NFT SYSTEM ────────────────────────────────────────────────────────────
  nft: {
    containerChance: 0.0001, // 0.01% (снижено вдвое)
    outcomes: {
      telegramGift: { chance: 0.99, label: 'Telegram Подарок' },
      uniqueShip:   { chance: 0.01, label: 'Уникальный корабль' },
    },
  },

  // ─── PIRATE EVENT ──────────────────────────────────────────────────────────
  pirates: {
    chance: 0.05,
    fightWinChance: 0.5,
    escapeCostStars: 10,
    winCreditBonusMultiplier: 0.10,
    defeatCooldownMinutes: 30,
  },

  // ─── SHOP ITEMS ────────────────────────────────────────────────────────────
  shopItems: {
    signal_amplifier_basic: {
      label: 'Усилитель сигнала (Базовый)',   icon: '📡',
      description: '+5% к вероятности редких находок на 2 часа',
      costCredits: 1500, costStars: null,
      buffType: 'signal_amplifier', durationHours: 2,
      metadata: { tier: 'basic', rarityBonus: 0.05 },
    },
    signal_amplifier_advanced: {
      label: 'Усилитель сигнала (Улучшенный)', icon: '📡',
      description: '+8% к вероятности редких находок на 2 часа',
      costCredits: 2000, costStars: null,
      buffType: 'signal_amplifier', durationHours: 2,
      metadata: { tier: 'advanced', rarityBonus: 0.08 },
    },
    signal_amplifier_star: {
      label: 'Усилитель сигнала (Звёздный)', icon: '📡',
      description: '+12% к вероятности редких находок на 2 часа',
      costCredits: null, costStars: 15,
      buffType: 'signal_amplifier', durationHours: 2,
      metadata: { tier: 'star', rarityBonus: 0.12 },
    },
    stealth_module: {
      label: 'Маскировочный модуль', icon: '🛡️',
      description: 'Блокирует пиратов на 24 часа',
      costCredits: 4000, costStars: null,
      buffType: 'stealth_module', durationHours: 24, metadata: {},
    },
    turbo_engine: {
      label: 'Турбо-двигатель', icon: '⚡',
      description: '-50% время экспедиций на 1 час',
      costCredits: null, costStars: 25,
      buffType: 'turbo_engine', durationHours: 1,
      metadata: { durationMultiplier: 0.5 },
    },
    insurance_policy: {
      label: 'Страховой полис', icon: '📜',
      description: 'Если выпадает обычная (Common) находка — автоматически делает перебросок. Действует 24 часа',
      costCredits: 1500, costStars: null,
      buffType: 'insurance_policy', durationHours: 24, metadata: {},
    },
    cartographer: {
      label: 'Картограф', icon: '🗺️',
      description: 'Гарантирует 100% повтор последнего типа находки, 3 экспедиции',
      costCredits: 1000, costStars: null,
      buffType: 'cartographer', durationHours: null, usesTotal: 3, metadata: {},
    },
    quantum_locator: {
      label: 'Квантовый локатор', icon: '🔭',
      description: '+50% к двум высшим редкостям текущей вселенной, 100 экспедиций',
      costCredits: 30000, costStars: null,
      buffType: 'quantum_locator', durationHours: null, usesTotal: 100,
      minLevel: 15, metadata: {},
    },
    remote_scanner: {
      label: 'Удалённый сканер', icon: '🛰️',
      description: 'Расшифровывает данные одного неизвестного астероида из инвентаря',
      costCredits: null, costStars: 10,
      buffType: 'remote_scanner', durationHours: null, usesTotal: 1,
      stackable: true, metadata: {},
    },
    blitz_cooldown_reducer: {
      label: 'Ускоренная зарядка', icon: '⚡',
      description: '-25% к кулдауну следующего блиц-рейда',
      costCredits: 3000, costStars: null,
      buffType: 'blitz_cooldown_reducer', durationHours: null, usesTotal: 1,
      metadata: { cooldownFactor: 0.75 },
    },
    blitz_stabilizer: {
      label: 'Нано-стабилизатор', icon: '🛡️',
      description: 'Первые 5 свайпов гарантированно без взрыва. На 6 блиц-рейдов',
      costCredits: null, costStars: 30,
      buffType: 'blitz_stabilizer', durationHours: null, usesTotal: 6,
      stackable: false,
      metadata: { swipesProtected: 5 },
    },
  },

  // ─── STAR UPGRADES (persistent, multi-level, bought once) ────────────────
  starUpgrades: {
    pirate_suppressor: {
      id: 'pirate_suppressor',
      label: 'Подавитель пиратского сигнала',
      icon: '🏴‍☠️',
      description: 'Снижает вероятность нападения пиратов на 1% за уровень',
      maxLevel: 4,
      costStarsPerLevel: 25,
      effect: 'pirate_chance_reduction', // -1% per level
    },
    research_lab: {
      id: 'research_lab',
      label: 'Исследовательская лаборатория',
      icon: '🔬',
      description: '+10% опыта со всех находок',
      maxLevel: 1,
      costStarsPerLevel: 50,
      effect: 'xp_bonus', // +10%
    },
    gravity_stabilizer: {
      id: 'gravity_stabilizer',
      label: 'Гравитационный стабилизатор',
      icon: '⚙️',
      description: 'Сокращает время каждой экспедиции на 10%',
      maxLevel: 1,
      costStarsPerLevel: 150,
      effect: 'expedition_time_mult', // 0.9
    },
    advanced_scanner: {
      id: 'advanced_scanner',
      label: 'Продвинутый сканирующий модуль',
      icon: '🔭',
      description: 'Повышает шанс Редкий +2% и Эпический +1% за уровень',
      maxLevel: 5,
      costStarsPerLevel: 20,
      requiresScannerLevel: 5,
      effect: 'scanner_rarity_bonus',
    },
  },

  // ─── ECONOMY — base XP per find TYPE (before rarity × zone multipliers) ────
  economy: {
    baseXP: { debris: 15, artifact: 25, creature: 20, anomaly: 30, asteroid: 10 },
  },

  // ─── ASTEROID RESOURCES by rarity ─────────────────────────────────────────
  asteroidResources: {
    common:    [
      { id: 'iron',      name: 'Железо',            pricePerTon: 6  },
      { id: 'nickel',    name: 'Никель',             pricePerTon: 8  },
      { id: 'silicate',  name: 'Силикаты',           pricePerTon: 4  },
    ],
    rare:      [
      { id: 'titanium',  name: 'Титан',              pricePerTon: 14 },
      { id: 'cobalt',    name: 'Кобальт',            pricePerTon: 16 },
    ],
    epic:      [
      { id: 'rare_earth',name: 'Редкоземельные',     pricePerTon: 28 },
      { id: 'iridium',   name: 'Иридий',             pricePerTon: 36 },
    ],
    legendary: [
      { id: 'platinum',  name: 'Платина',            pricePerTon: 80 },
    ],
    mythical:  [
      { id: 'antimatter',name: 'Антиматерия',        pricePerTon: 300 },
    ],
  },

  // ─── REFERRAL SYSTEM ───────────────────────────────────────────────────────
  referral: {
    // Activation requirements (referral must meet ONE of these)
    minExpeditionsForActivation: 3,
    minCreditsForActivation: 500,

    // One-time rewards on activation
    referrerRewardCredits: 500,
    referralRewardCredits: 300,
    rewardDelayMs: 3600000, // 1 hour delay for anti-abuse

    // Passive income percentages
    baseCreditsPercent: 5,   // % of referral's sell income
    baseStarsPercent: 5,     // % of referral's star topups
    maxTotalPercent: 15,     // hard cap on final_percent (base + rank bonus)

    // Stars income mode: 'stars' = pay in stars, 'credits' = convert to credits
    starsIncomeMode: 'stars',
    starsToCreditsRate: 100, // 1 star = 100 credits (if mode='credits')

    // Daily limits (base, before rank bonuses)
    maxCreditsPerDay: 5000,
    maxStarsPerDay: 50,

    // Rank tiers: min = active referrals needed
    ranks: [
      { min: 1,  bonusPercent: 0, creditsCap: 5000,  starsCap: 50 },
      { min: 5,  bonusPercent: 2, creditsCap: 8000,  starsCap: 80 },
      { min: 15, bonusPercent: 3, creditsCap: 12000, starsCap: 120 },
      { min: 30, bonusPercent: 5, creditsCap: 20000, starsCap: 200 },
      { min: 75, bonusPercent: 8, creditsCap: 40000, starsCap: 400 },
    ],

    // Milestones: one-time star rewards for active referral counts
    milestones: [
      { count: 1,  rewardStars: 1 },
      { count: 3,  rewardStars: 2 },
      { count: 5,  rewardStars: 5 },
      { count: 10, rewardStars: 10 },
      { count: 25, rewardStars: 25 },
      { count: 50, rewardStars: 50 },
    ],

    // Anti-abuse
    minTelegramAccountAgeDays: 3,   // minimum age of TG account (checked if data available)
  },

  // ─── FACTIONS & QUESTS ────────────────────────────────────────────────────
  factions: {
    list: [
      {
        id: 'bioengineers',
        name: 'Биоинженеры',
        nameEn: 'Bioengineers',
        icon: '🔬',
        description: 'Изучение существ и аномалий',
        descriptionEn: 'Studying creatures and anomalies',
        active: true,
        minLevel: 1,
      },
      {
        id: 'tech_institute',
        name: 'Технологический институт',
        nameEn: 'Technological Institute',
        icon: '⚙️',
        description: 'Исследование артефактов и обломков',
        descriptionEn: 'Researching artifacts and debris',
        active: true,
        minLevel: 1,
      },
      {
        id: 'industrial_league',
        name: 'Промышленная лига',
        nameEn: 'Industrial League',
        icon: '🏭',
        description: 'Добыча ресурсов и металлов',
        descriptionEn: 'Resource mining and metals',
        active: false, // Unlocked when drills are added
        minLevel: 1,
      },
      {
        id: 'navigators_order',
        name: 'Орден навигаторов',
        nameEn: 'Navigators Order',
        icon: '🧭',
        description: 'Исследования и экспедиции',
        descriptionEn: 'Exploration and expeditions',
        active: true,
        minLevel: 1,
      },
      {
        id: 'black_market',
        name: 'Чёрный рынок',
        nameEn: 'Black Market',
        icon: '🕶️',
        description: 'Контрабанда и редкие сделки',
        descriptionEn: 'Smuggling and rare deals',
        active: true,
        minLevel: 20,
        universe: 1,
      },

      // ── Universe 2 factions ─────────────────────────────────────────────────
      {
        id: 'chroniclers',
        name: 'Хронисты',
        nameEn: 'Chroniclers',
        icon: 'chr',
        description: 'Изучение сущностей и эхо-следов',
        descriptionEn: 'Studying entities and echo traces',
        active: true,
        minLevel: 1,
        universe: 2,
      },
      {
        id: 'void_seekers',
        name: 'Пустотники',
        nameEn: 'Void Seekers',
        icon: 'vs',
        description: 'Охота за реликвиями и картографирование разломов',
        descriptionEn: 'Hunting relics and mapping rifts',
        active: true,
        minLevel: 1,
        universe: 2,
      },
      {
        id: 'resonators',
        name: 'Резонаторы',
        nameEn: 'Resonators',
        icon: 'res',
        description: 'Экспедиции и добыча астероидов',
        descriptionEn: 'Expeditions and asteroid mining',
        active: true,
        minLevel: 1,
        universe: 2,
      },
      {
        id: 'haulers',
        name: 'Дальнобойщики',
        nameEn: 'Haulers',
        icon: 'haul',
        description: 'Межвселенная торговля товарами из U1',
        descriptionEn: 'Cross-universe trade in U1 goods',
        active: true,
        minLevel: 20,
        universe: 2,
      },
    ],

    // Reputation thresholds → label
    reputationTiers: [
      { min: -1000, label: 'Враг',        labelEn: 'Enemy',       icon: '💀' },
      { min: -250,  label: 'Недоверие',   labelEn: 'Distrust',    icon: '⚠️' },
      { min: 0,     label: 'Нейтралитет', labelEn: 'Neutral',     icon: '➖' },
      { min: 250,   label: 'Партнёр',     labelEn: 'Partner',     icon: '🤝' },
      { min: 500,   label: 'Союзник',     labelEn: 'Ally',        icon: '⭐' },
      { min: 750,   label: 'Элита',       labelEn: 'Elite',       icon: '👑' },
    ],

    // Reputation → reward multiplier
    reputationMultipliers: [
      { min: 0,    mult: 1.00 },
      { min: 250,  mult: 1.05 },
      { min: 500,  mult: 1.10 },
      { min: 750,  mult: 1.15 },
      { min: 1000, mult: 1.20 },
    ],

    // Passive reputation decay: -decayAmount/day for reputation > decayThreshold
    decayThreshold: 500,
    decayAmount: 2,

    // Faction conflicts: completing quests for one faction may affect another
    conflicts: [
      // U1
      { source: 'bioengineers', target: 'industrial_league', ratio: -0.4 },
      { source: 'industrial_league', target: 'bioengineers', ratio: -0.4 },
      { source: 'black_market', target: 'navigators_order', ratio: -0.3 },
      { source: 'black_market', target: 'tech_institute', ratio: -0.2 },
      // U2
      { source: 'chroniclers', target: 'void_seekers', ratio: -0.3 },
      { source: 'void_seekers', target: 'chroniclers', ratio: -0.3 },
      { source: 'haulers', target: 'chroniclers', ratio: -0.2 },
    ],

    maxReputation: 1000,
    minReputation: -1000,
  },

  quests: {
    daily: { count: 3, refreshHours: 24, freeRerolls: 1 },
    weekly: { count: 2, refreshHours: 168, freeRerolls: 0 },
    repeatable: { count: 1, refreshHours: 24, freeRerolls: 0 },
    special: { baseChancePercent: 5, maxActive: 1, rewardMultiplier: 1.5, amountMultiplier: 1.2 },

    // Buyout system (daily quests only)
    buyout: {
      enabled: true,
      costMultiplier: 2.0,      // N× market value of required items
      maxPerDay: 1,
      allowedTypes: ['daily'],   // only daily quests can be bought out
    },

    // Minimum reward = minRewardMultiplier × item market value × quantity
    minRewardMultiplier: 1.5,

    // Quest templates
    //
    // Amount ranges per schedule:
    //   daily:   Common 1-10, Rare 1-5, Epic 1-2
    //   weekly:  Common 20-70, Rare 15-50, Epic 10-35, Legendary 1-10, Mythical 1-3
    //   special: Same as weekly, but has item rewards + unique styling
    //
    // Legendary/Mythical rarities only appear in weekly + special quests.
    // Item rewards (bioscanner etc.) only drop from special quests.
    //
    templates: [
      // ── Bioengineers ──────────────────────────────────────────────────────
      // Deliver creature — daily per rarity
      {
        id: 'bio_deliver_creature_common',
        faction: 'bioengineers',
        type: 'deliver_object',
        targetType: 'creature',
        targetRarities: ['common'],
        amountRange: [4, 8],
        creditRange: [0, 0],
        xpRange: [40, 100],
        reputationGain: [10, 20],
        questTypes: ['daily'],
        nameRu: 'Биоматериал',
        nameEn: 'Biomaterial',
        descRu: 'Фракция нуждается в образцах для исследований',
        descEn: 'The faction needs specimens for research',
      },
      {
        id: 'bio_deliver_creature_rare',
        faction: 'bioengineers',
        type: 'deliver_object',
        targetType: 'creature',
        targetRarities: ['rare'],
        amountRange: [1, 3],
        creditRange: [0, 0],
        xpRange: [80, 200],
        reputationGain: [18, 35],
        questTypes: ['daily'],
        nameRu: 'Биоматериал',
        nameEn: 'Biomaterial',
        descRu: 'Редкие образцы для углублённого изучения',
        descEn: 'Rare specimens for advanced study',
      },
      // Deliver creature — weekly per rarity
      {
        id: 'bio_deliver_creature_rare_w',
        faction: 'bioengineers',
        type: 'deliver_object',
        targetType: 'creature',
        targetRarities: ['rare'],
        amountRange: [7, 14],
        creditRange: [0, 0],
        xpRange: [200, 520],
        reputationGain: [32, 60],
        questTypes: ['weekly'],
        nameRu: 'Крупная поставка',
        nameEn: 'Large delivery',
        descRu: 'Масштабный заказ на биоматериалы для лаборатории',
        descEn: 'Large-scale lab biomaterial order',
      },
      {
        id: 'bio_deliver_creature_epic_w',
        faction: 'bioengineers',
        type: 'deliver_object',
        targetType: 'creature',
        targetRarities: ['epic'],
        amountRange: [2, 5],
        creditRange: [0, 0],
        xpRange: [360, 760],
        reputationGain: [44, 76],
        questTypes: ['weekly'],
        nameRu: 'Исключительные образцы',
        nameEn: 'Exceptional specimens',
        descRu: 'Эпические образцы для секретных разработок',
        descEn: 'Epic specimens for classified research',
      },
      {
        id: 'bio_deliver_creature_legendary_w',
        faction: 'bioengineers',
        type: 'deliver_object',
        targetType: 'creature',
        targetRarities: ['legendary'],
        amountRange: [1, 1],
        creditRange: [0, 0],
        xpRange: [560, 900],
        reputationGain: [56, 90],
        questTypes: ['weekly'],
        nameRu: 'Легендарный экземпляр',
        nameEn: 'Legendary specimen',
        descRu: 'Единственный в своём роде — для архива Ордена',
        descEn: 'One of a kind — for the Order\'s archive',
      },
      // Find anomaly — daily per rarity
      {
        id: 'bio_find_anomaly_common',
        faction: 'bioengineers',
        type: 'find_object',
        targetType: 'anomaly',
        targetRarities: ['common'],
        amountRange: [4, 8],
        creditRange: [0, 0],
        xpRange: [30, 80],
        reputationGain: [8, 16],
        questTypes: ['daily'],
        nameRu: 'Поиск аномалий',
        nameEn: 'Anomaly search',
        descRu: 'Обнаружьте аномалии в ходе экспедиций',
        descEn: 'Discover anomalies during expeditions',
      },
      {
        id: 'bio_find_anomaly_rare',
        faction: 'bioengineers',
        type: 'find_object',
        targetType: 'anomaly',
        targetRarities: ['rare'],
        amountRange: [2, 4],
        creditRange: [0, 0],
        xpRange: [60, 160],
        reputationGain: [14, 28],
        questTypes: ['daily'],
        nameRu: 'Редкие аномалии',
        nameEn: 'Rare anomalies',
        descRu: 'Зафиксируйте нестандартные аномальные явления',
        descEn: 'Record unusual anomalous phenomena',
      },
      // Find anomaly — weekly per rarity
      {
        id: 'bio_find_anomaly_rare_w',
        faction: 'bioengineers',
        type: 'find_object',
        targetType: 'anomaly',
        targetRarities: ['rare'],
        amountRange: [8, 16],
        creditRange: [0, 0],
        xpRange: [180, 440],
        reputationGain: [30, 56],
        questTypes: ['weekly'],
        nameRu: 'Аномальный мониторинг',
        nameEn: 'Anomaly monitoring',
        descRu: 'Серия экспедиций для картографирования аномалий',
        descEn: 'Expedition series for anomaly mapping',
      },
      {
        id: 'bio_find_anomaly_epic_w',
        faction: 'bioengineers',
        type: 'find_object',
        targetType: 'anomaly',
        targetRarities: ['epic'],
        amountRange: [2, 5],
        creditRange: [0, 0],
        xpRange: [280, 640],
        reputationGain: [38, 68],
        questTypes: ['weekly'],
        nameRu: 'Эпические аномалии',
        nameEn: 'Epic anomalies',
        descRu: 'Зафиксируйте редчайшие аномальные явления',
        descEn: 'Record the rarest anomalous phenomena',
      },
      {
        id: 'bio_find_anomaly_legendary_w',
        faction: 'bioengineers',
        type: 'find_object',
        targetType: 'anomaly',
        targetRarities: ['legendary'],
        amountRange: [1, 2],
        creditRange: [0, 0],
        xpRange: [440, 780],
        reputationGain: [50, 84],
        questTypes: ['weekly'],
        nameRu: 'Легендарная аномалия',
        nameEn: 'Legendary anomaly',
        descRu: 'Явление, которое меняет научные парадигмы',
        descEn: 'A phenomenon that reshapes scientific paradigms',
      },
      // Sell creature — daily per rarity
      {
        id: 'bio_sell_creature_common',
        faction: 'bioengineers',
        type: 'sell_object',
        targetType: 'creature',
        targetRarities: ['common'],
        amountRange: [5, 10],
        creditRange: [0, 0],
        xpRange: [30, 80],
        reputationGain: [6, 14],
        questTypes: ['daily'],
        nameRu: 'Продать образцы',
        nameEn: 'Sell specimens',
        descRu: 'Продайте образцы на рынке — фракция компенсирует',
        descEn: 'Sell specimens on the market — the faction will compensate',
      },
      {
        id: 'bio_sell_creature_rare',
        faction: 'bioengineers',
        type: 'sell_object',
        targetType: 'creature',
        targetRarities: ['rare'],
        amountRange: [2, 4],
        creditRange: [0, 0],
        xpRange: [60, 140],
        reputationGain: [12, 24],
        questTypes: ['daily'],
        nameRu: 'Редкие образцы',
        nameEn: 'Rare specimens',
        descRu: 'Лабораторный запрос на редких существ',
        descEn: 'Lab request for rare creatures',
      },

      // ── Technological Institute ───────────────────────────────────────────
      // Deliver artifact — daily per rarity
      {
        id: 'tech_deliver_artifact_common',
        faction: 'tech_institute',
        type: 'deliver_object',
        targetType: 'artifact',
        targetRarities: ['common'],
        amountRange: [4, 8],
        creditRange: [0, 0],
        xpRange: [45, 110],
        reputationGain: [10, 22],
        questTypes: ['daily'],
        nameRu: 'Артефакты',
        nameEn: 'Artifacts',
        descRu: 'Институту нужны артефакты для декодирования',
        descEn: 'Institute needs artifacts for decoding',
      },
      {
        id: 'tech_deliver_artifact_rare',
        faction: 'tech_institute',
        type: 'deliver_object',
        targetType: 'artifact',
        targetRarities: ['rare'],
        amountRange: [1, 3],
        creditRange: [0, 0],
        xpRange: [85, 210],
        reputationGain: [20, 38],
        questTypes: ['daily'],
        nameRu: 'Редкий артефакт',
        nameEn: 'Rare artifact',
        descRu: 'Требуется для дешифровки древних протоколов',
        descEn: 'Required for deciphering ancient protocols',
      },
      // Deliver artifact — weekly per rarity
      {
        id: 'tech_deliver_artifact_rare_w',
        faction: 'tech_institute',
        type: 'deliver_object',
        targetType: 'artifact',
        targetRarities: ['rare'],
        amountRange: [7, 14],
        creditRange: [0, 0],
        xpRange: [210, 540],
        reputationGain: [34, 62],
        questTypes: ['weekly'],
        nameRu: 'Массовая поставка',
        nameEn: 'Mass delivery',
        descRu: 'Крупный заказ для исследовательского корпуса',
        descEn: 'Bulk order for the research corps',
      },
      {
        id: 'tech_deliver_artifact_epic_w',
        faction: 'tech_institute',
        type: 'deliver_object',
        targetType: 'artifact',
        targetRarities: ['epic'],
        amountRange: [2, 5],
        creditRange: [0, 0],
        xpRange: [370, 780],
        reputationGain: [46, 78],
        questTypes: ['weekly'],
        nameRu: 'Эпические артефакты',
        nameEn: 'Epic artifacts',
        descRu: 'Исключительная ценность для архивов Института',
        descEn: 'Exceptional value for the Institute\'s archives',
      },
      {
        id: 'tech_deliver_artifact_legendary_w',
        faction: 'tech_institute',
        type: 'deliver_object',
        targetType: 'artifact',
        targetRarities: ['legendary'],
        amountRange: [1, 1],
        creditRange: [0, 0],
        xpRange: [580, 920],
        reputationGain: [58, 92],
        questTypes: ['weekly'],
        nameRu: 'Легендарный артефакт',
        nameEn: 'Legendary artifact',
        descRu: 'Реликт до-цивилизационной эпохи',
        descEn: 'A relic from the pre-civilisation era',
      },
      // Find debris — daily per rarity
      {
        id: 'tech_find_debris_common',
        faction: 'tech_institute',
        type: 'find_object',
        targetType: 'debris',
        targetRarities: ['common'],
        amountRange: [5, 10],
        creditRange: [0, 0],
        xpRange: [30, 75],
        reputationGain: [8, 16],
        questTypes: ['daily'],
        nameRu: 'Обломки',
        nameEn: 'Debris',
        descRu: 'Обнаружьте обломки для технического анализа',
        descEn: 'Discover debris for technical analysis',
      },
      {
        id: 'tech_find_debris_rare',
        faction: 'tech_institute',
        type: 'find_object',
        targetType: 'debris',
        targetRarities: ['rare'],
        amountRange: [2, 5],
        creditRange: [0, 0],
        xpRange: [65, 165],
        reputationGain: [14, 30],
        questTypes: ['daily'],
        nameRu: 'Ценные обломки',
        nameEn: 'Valuable debris',
        descRu: 'Фрагменты продвинутых технологий',
        descEn: 'Fragments of advanced technology',
      },
      // Find debris — weekly per rarity
      {
        id: 'tech_find_debris_rare_w',
        faction: 'tech_institute',
        type: 'find_object',
        targetType: 'debris',
        targetRarities: ['rare'],
        amountRange: [9, 18],
        creditRange: [0, 0],
        xpRange: [190, 460],
        reputationGain: [32, 58],
        questTypes: ['weekly'],
        nameRu: 'Сканирование обломков',
        nameEn: 'Debris scan',
        descRu: 'Масштабная экспедиция по сбору фрагментов',
        descEn: 'Large-scale fragment collection expedition',
      },
      {
        id: 'tech_find_debris_epic_w',
        faction: 'tech_institute',
        type: 'find_object',
        targetType: 'debris',
        targetRarities: ['epic'],
        amountRange: [2, 5],
        creditRange: [0, 0],
        xpRange: [290, 660],
        reputationGain: [40, 72],
        questTypes: ['weekly'],
        nameRu: 'Эпические обломки',
        nameEn: 'Epic debris',
        descRu: 'Реликвии технологий ушедших цивилизаций',
        descEn: 'Relics of lost civilization technology',
      },
      // Sell artifact — daily per rarity
      {
        id: 'tech_sell_artifact_common',
        faction: 'tech_institute',
        type: 'sell_object',
        targetType: 'artifact',
        targetRarities: ['common'],
        amountRange: [5, 10],
        creditRange: [0, 0],
        xpRange: [30, 80],
        reputationGain: [6, 14],
        questTypes: ['daily'],
        nameRu: 'Продать артефакты',
        nameEn: 'Sell artifacts',
        descRu: 'Продайте артефакты — институт доплатит',
        descEn: 'Sell artifacts — institute will pay extra',
      },
      {
        id: 'tech_sell_artifact_rare',
        faction: 'tech_institute',
        type: 'sell_object',
        targetType: 'artifact',
        targetRarities: ['rare'],
        amountRange: [2, 4],
        creditRange: [0, 0],
        xpRange: [65, 150],
        reputationGain: [12, 26],
        questTypes: ['daily'],
        nameRu: 'Редкие артефакты',
        nameEn: 'Rare artifacts',
        descRu: 'Институт выкупает редкие технологические артефакты',
        descEn: 'Institute buys rare technological artifacts',
      },

      // ── Navigators Order ──────────────────────────────────────────────────
      // Expeditions — daily (two variants for variety)
      {
        id: 'nav_expeditions_daily_sm',
        faction: 'navigators_order',
        type: 'expeditions',
        targetType: null,
        targetRarities: [],
        amountRange: [5, 8],
        creditRange: [0, 0],
        xpRange: [80, 180],
        reputationGain: [12, 22],
        questTypes: ['daily'],
        nameRu: 'Патрулирование',
        nameEn: 'Patrol',
        descRu: 'Орден отправляет вас в разведывательные вылазки',
        descEn: 'The Order sends you on recon sorties',
      },
      {
        id: 'nav_expeditions_daily_lg',
        faction: 'navigators_order',
        type: 'expeditions',
        targetType: null,
        targetRarities: [],
        amountRange: [9, 14],
        creditRange: [0, 0],
        xpRange: [140, 300],
        reputationGain: [18, 32],
        questTypes: ['daily'],
        nameRu: 'Расширенный патруль',
        nameEn: 'Extended patrol',
        descRu: 'Более широкий охват для картографирования зон',
        descEn: 'Wider coverage for zone mapping',
      },
      // Expeditions — repeatable
      {
        id: 'nav_expeditions_repeatable',
        faction: 'navigators_order',
        type: 'expeditions',
        targetType: null,
        targetRarities: [],
        amountRange: [5, 10],
        creditRange: [0, 0],
        xpRange: [60, 140],
        reputationGain: [8, 18],
        questTypes: ['repeatable'],
        nameRu: 'Постоянный мониторинг',
        nameEn: 'Continuous monitoring',
        descRu: 'Непрерывный мониторинг секторов для Ордена',
        descEn: 'Continuous sector monitoring for the Order',
      },
      // Expeditions — weekly (two difficulty tiers)
      {
        id: 'nav_expeditions_weekly_sm',
        faction: 'navigators_order',
        type: 'expeditions',
        targetType: null,
        targetRarities: [],
        amountRange: [50, 70],
        creditRange: [0, 0],
        xpRange: [400, 800],
        reputationGain: [40, 68],
        questTypes: ['weekly'],
        nameRu: 'Серия экспедиций',
        nameEn: 'Expedition series',
        descRu: 'Масштабная разведка для Ордена навигаторов',
        descEn: 'Large-scale recon for the Navigators Order',
      },
      {
        id: 'nav_expeditions_weekly_lg',
        faction: 'navigators_order',
        type: 'expeditions',
        targetType: null,
        targetRarities: [],
        amountRange: [80, 120],
        creditRange: [0, 0],
        xpRange: [600, 1100],
        reputationGain: [52, 84],
        questTypes: ['weekly'],
        nameRu: 'Большая разведка',
        nameEn: 'Grand recon',
        descRu: 'Полноценная картографическая операция',
        descEn: 'Full-scale cartographic operation',
      },
      // Find any — daily per rarity
      {
        id: 'nav_find_any_common',
        faction: 'navigators_order',
        type: 'find_object',
        targetType: null,
        targetRarities: ['common'],
        amountRange: [5, 10],
        creditRange: [0, 0],
        xpRange: [35, 85],
        reputationGain: [8, 15],
        questTypes: ['daily'],
        nameRu: 'Сбор находок',
        nameEn: 'Collect finds',
        descRu: 'Обнаружьте объекты в секторе',
        descEn: 'Discover objects in the sector',
      },
      {
        id: 'nav_find_any_rare',
        faction: 'navigators_order',
        type: 'find_object',
        targetType: null,
        targetRarities: ['rare'],
        amountRange: [2, 4],
        creditRange: [0, 0],
        xpRange: [70, 170],
        reputationGain: [14, 28],
        questTypes: ['daily'],
        nameRu: 'Редкие находки',
        nameEn: 'Rare finds',
        descRu: 'Зафиксируйте редкие объекты в экспедициях',
        descEn: 'Record rare objects during expeditions',
      },
      // Find any — weekly per rarity
      {
        id: 'nav_find_any_rare_w',
        faction: 'navigators_order',
        type: 'find_object',
        targetType: null,
        targetRarities: ['rare'],
        amountRange: [8, 16],
        creditRange: [0, 0],
        xpRange: [200, 480],
        reputationGain: [32, 60],
        questTypes: ['weekly'],
        nameRu: 'Исследование сектора',
        nameEn: 'Sector research',
        descRu: 'Систематическое изучение аномалий и объектов',
        descEn: 'Systematic study of anomalies and objects',
      },
      {
        id: 'nav_find_any_epic_w',
        faction: 'navigators_order',
        type: 'find_object',
        targetType: null,
        targetRarities: ['epic'],
        amountRange: [2, 5],
        creditRange: [0, 0],
        xpRange: [300, 680],
        reputationGain: [42, 74],
        questTypes: ['weekly'],
        nameRu: 'Ценные открытия',
        nameEn: 'Valuable discoveries',
        descRu: 'Эпические находки для банка данных Ордена',
        descEn: 'Epic finds for the Order\'s data bank',
      },

      // ── Black Market ──────────────────────────────────────────────────────
      // Sell — daily, per rarity (req 50 rep)
      {
        id: 'bm_sell_rare',
        faction: 'black_market',
        type: 'sell_object',
        targetType: null,
        targetRarities: ['rare'],
        amountRange: [2, 4],
        creditRange: [0, 0],
        xpRange: [65, 165],
        reputationGain: [14, 28],
        starChance: 0.10,
        starRange: [1, 2],
        questTypes: ['daily'],
        nameRu: 'Контрабанда',
        nameEn: 'Smuggling',
        descRu: 'Продайте редкие предметы через чёрный рынок',
        descEn: 'Sell rare items through the black market',
        reputationRequirements: [{ factionId: 'black_market', operator: '>=', value: 50 }],
        reputationPenalties: [{ factionId: 'tech_institute', amount: 5 }],
      },
      {
        id: 'bm_sell_epic',
        faction: 'black_market',
        type: 'sell_object',
        targetType: null,
        targetRarities: ['epic'],
        amountRange: [1, 2],
        creditRange: [0, 0],
        xpRange: [120, 280],
        reputationGain: [22, 42],
        starChance: 0.15,
        starRange: [1, 2],
        questTypes: ['daily'],
        nameRu: 'Ценный товар',
        nameEn: 'Valuable goods',
        descRu: 'Эпические предметы высоко ценятся на чёрном рынке',
        descEn: 'Epic items are highly valued on the black market',
        reputationRequirements: [{ factionId: 'black_market', operator: '>=', value: 50 }],
        reputationPenalties: [{ factionId: 'tech_institute', amount: 8 }],
      },
      // Sell — weekly, per rarity (req 100 rep)
      {
        id: 'bm_sell_rare_w',
        faction: 'black_market',
        type: 'sell_object',
        targetType: null,
        targetRarities: ['rare'],
        amountRange: [6, 12],
        creditRange: [0, 0],
        xpRange: [200, 500],
        reputationGain: [28, 54],
        starChance: 0.20,
        starRange: [1, 3],
        questTypes: ['weekly'],
        nameRu: 'Крупная партия',
        nameEn: 'Large shipment',
        descRu: 'Крупная сделка с чёрным рынком',
        descEn: 'Large deal with the black market',
        reputationRequirements: [{ factionId: 'black_market', operator: '>=', value: 100 }],
        reputationPenalties: [{ factionId: 'tech_institute', amount: 10 }, { factionId: 'navigators_order', amount: 5 }],
      },
      {
        id: 'bm_sell_epic_w',
        faction: 'black_market',
        type: 'sell_object',
        targetType: null,
        targetRarities: ['epic'],
        amountRange: [2, 4],
        creditRange: [0, 0],
        xpRange: [340, 720],
        reputationGain: [40, 72],
        starChance: 0.25,
        starRange: [2, 4],
        questTypes: ['weekly'],
        nameRu: 'Премиум партия',
        nameEn: 'Premium shipment',
        descRu: 'Эпические предметы для VIP-покупателей рынка',
        descEn: 'Epic items for the market\'s VIP buyers',
        reputationRequirements: [{ factionId: 'black_market', operator: '>=', value: 100 }],
        reputationPenalties: [{ factionId: 'tech_institute', amount: 14 }, { factionId: 'navigators_order', amount: 7 }],
      },
      // Sell legendary — weekly (req 200 rep)
      {
        id: 'bm_sell_legendary_w',
        faction: 'black_market',
        type: 'sell_object',
        targetType: null,
        targetRarities: ['legendary'],
        amountRange: [1, 1],
        creditRange: [0, 0],
        xpRange: [500, 860],
        reputationGain: [52, 86],
        starChance: 0.35,
        starRange: [2, 5],
        questTypes: ['weekly'],
        nameRu: 'Легендарная сделка',
        nameEn: 'Legendary deal',
        descRu: 'Только избранным доверяют такой товар',
        descEn: 'Only the trusted are offered such goods',
        reputationRequirements: [{ factionId: 'black_market', operator: '>=', value: 200 }],
        reputationPenalties: [{ factionId: 'tech_institute', amount: 20 }, { factionId: 'navigators_order', amount: 12 }],
      },
      // Find — weekly (req 150 rep)
      {
        id: 'bm_find_epic_w',
        faction: 'black_market',
        type: 'find_object',
        targetType: null,
        targetRarities: ['epic'],
        amountRange: [2, 5],
        creditRange: [0, 0],
        xpRange: [260, 580],
        reputationGain: [36, 64],
        starChance: 0.20,
        starRange: [1, 3],
        questTypes: ['weekly'],
        nameRu: 'Ценный груз',
        nameEn: 'Valuable cargo',
        descRu: 'Найдите эпические предметы для посредника',
        descEn: 'Find epic items for the broker',
        reputationRequirements: [{ factionId: 'black_market', operator: '>=', value: 150 }],
      },
      {
        id: 'bm_find_legendary_w',
        faction: 'black_market',
        type: 'find_object',
        targetType: null,
        targetRarities: ['legendary'],
        amountRange: [1, 2],
        creditRange: [0, 0],
        xpRange: [420, 800],
        reputationGain: [48, 82],
        starChance: 0.30,
        starRange: [2, 5],
        questTypes: ['weekly'],
        nameRu: 'Легендарный товар',
        nameEn: 'Legendary goods',
        descRu: 'Найдите легендарную находку для особого клиента',
        descEn: 'Find a legendary discovery for a special client',
        reputationRequirements: [{ factionId: 'black_market', operator: '>=', value: 150 }],
      },

      // ═══════════════════════════════════════════════════════════════════════
      // UNIVERSE 2 QUEST TEMPLATES
      // Rarities: exotic < ancient < relic < hybrid < singularity
      // Reward currency: crystals (handled by questService._isU2Faction)
      // ═══════════════════════════════════════════════════════════════════════

      // ── Chroniclers (entity + echo) ───────────────────────────────────────
      // Deliver entity — daily
      {
        id: 'chr_deliver_entity_exotic_d',
        faction: 'chroniclers',
        type: 'deliver_object',
        targetType: 'entity',
        targetRarities: ['exotic'],
        amountRange: [4, 8],
        creditRange: [0, 0],
        xpRange: [40, 100],
        reputationGain: [10, 20],
        questTypes: ['daily'],
        nameRu: 'Биоматериал пустоты',
        nameEn: 'Void biomaterial',
        descRu: 'Хронистам нужны образцы сущностей для каталога',
        descEn: 'Chroniclers need entity specimens for the catalogue',
      },
      {
        id: 'chr_deliver_entity_ancient_d',
        faction: 'chroniclers',
        type: 'deliver_object',
        targetType: 'entity',
        targetRarities: ['ancient'],
        amountRange: [1, 3],
        creditRange: [0, 0],
        xpRange: [80, 200],
        reputationGain: [18, 35],
        questTypes: ['daily'],
        nameRu: 'Древняя форма жизни',
        nameEn: 'Ancient life form',
        descRu: 'Редкие сущности для углублённого хронического анализа',
        descEn: 'Rare entities for deep chronicle analysis',
      },
      // Deliver entity — weekly
      {
        id: 'chr_deliver_entity_ancient_w',
        faction: 'chroniclers',
        type: 'deliver_object',
        targetType: 'entity',
        targetRarities: ['ancient'],
        amountRange: [7, 14],
        creditRange: [0, 0],
        xpRange: [200, 520],
        reputationGain: [32, 60],
        questTypes: ['weekly'],
        nameRu: 'Крупный архив сущностей',
        nameEn: 'Large entity archive',
        descRu: 'Масштабный заказ на древние биоматериалы',
        descEn: 'Large-scale order for ancient biomaterial',
      },
      {
        id: 'chr_deliver_entity_relic_w',
        faction: 'chroniclers',
        type: 'deliver_object',
        targetType: 'entity',
        targetRarities: ['relic'],
        amountRange: [2, 5],
        creditRange: [0, 0],
        xpRange: [360, 760],
        reputationGain: [44, 76],
        questTypes: ['weekly'],
        nameRu: 'Реликтовые формы',
        nameEn: 'Relic life forms',
        descRu: 'Реликтовые сущности для секретного архива Хронистов',
        descEn: 'Relic entities for the Chroniclers\' classified archive',
      },
      {
        id: 'chr_deliver_entity_hybrid_w',
        faction: 'chroniclers',
        type: 'deliver_object',
        targetType: 'entity',
        targetRarities: ['hybrid'],
        amountRange: [1, 1],
        creditRange: [0, 0],
        xpRange: [560, 900],
        reputationGain: [56, 90],
        questTypes: ['weekly'],
        nameRu: 'Гибридный экземпляр',
        nameEn: 'Hybrid specimen',
        descRu: 'Уникальная гибридная сущность — для высшего архива',
        descEn: 'A unique hybrid entity — for the supreme archive',
      },
      // Find echo — daily
      {
        id: 'chr_find_echo_exotic_d',
        faction: 'chroniclers',
        type: 'find_object',
        targetType: 'echo',
        targetRarities: ['exotic'],
        amountRange: [4, 8],
        creditRange: [0, 0],
        xpRange: [30, 80],
        reputationGain: [8, 16],
        questTypes: ['daily'],
        nameRu: 'Сбор эхо-следов',
        nameEn: 'Echo trace collection',
        descRu: 'Зафиксируйте эхо-следы в ходе экспедиций',
        descEn: 'Record echo traces during expeditions',
      },
      {
        id: 'chr_find_echo_ancient_d',
        faction: 'chroniclers',
        type: 'find_object',
        targetType: 'echo',
        targetRarities: ['ancient'],
        amountRange: [2, 4],
        creditRange: [0, 0],
        xpRange: [60, 160],
        reputationGain: [14, 28],
        questTypes: ['daily'],
        nameRu: 'Древние эхо',
        nameEn: 'Ancient echoes',
        descRu: 'Обнаружьте эхо-следы древней эпохи',
        descEn: 'Discover echo traces from the ancient era',
      },
      // Find echo — weekly
      {
        id: 'chr_find_echo_ancient_w',
        faction: 'chroniclers',
        type: 'find_object',
        targetType: 'echo',
        targetRarities: ['ancient'],
        amountRange: [8, 16],
        creditRange: [0, 0],
        xpRange: [180, 440],
        reputationGain: [30, 56],
        questTypes: ['weekly'],
        nameRu: 'Мониторинг эхо',
        nameEn: 'Echo monitoring',
        descRu: 'Серия экспедиций для картографирования эхо-полей',
        descEn: 'Expedition series for echo field mapping',
      },
      {
        id: 'chr_find_echo_relic_w',
        faction: 'chroniclers',
        type: 'find_object',
        targetType: 'echo',
        targetRarities: ['relic'],
        amountRange: [2, 5],
        creditRange: [0, 0],
        xpRange: [280, 640],
        reputationGain: [38, 68],
        questTypes: ['weekly'],
        nameRu: 'Реликтовые эхо',
        nameEn: 'Relic echoes',
        descRu: 'Зафиксируйте древнейшие эхо-явления',
        descEn: 'Record the most ancient echo phenomena',
      },
      {
        id: 'chr_find_echo_hybrid_w',
        faction: 'chroniclers',
        type: 'find_object',
        targetType: 'echo',
        targetRarities: ['hybrid'],
        amountRange: [1, 2],
        creditRange: [0, 0],
        xpRange: [440, 780],
        reputationGain: [50, 84],
        questTypes: ['weekly'],
        nameRu: 'Гибридное эхо',
        nameEn: 'Hybrid echo',
        descRu: 'Явление, меняющее парадигмы хронической науки',
        descEn: 'A phenomenon reshaping chronicle science paradigms',
      },
      // Sell entity — daily
      {
        id: 'chr_sell_entity_exotic_d',
        faction: 'chroniclers',
        type: 'sell_object',
        targetType: 'entity',
        targetRarities: ['exotic'],
        amountRange: [5, 10],
        creditRange: [0, 0],
        xpRange: [30, 80],
        reputationGain: [6, 14],
        questTypes: ['daily'],
        nameRu: 'Сдать образцы',
        nameEn: 'Submit specimens',
        descRu: 'Передайте сущностей на рынок — Хронисты компенсируют',
        descEn: 'Submit entities to the market — Chroniclers will compensate',
      },
      {
        id: 'chr_sell_entity_ancient_d',
        faction: 'chroniclers',
        type: 'sell_object',
        targetType: 'entity',
        targetRarities: ['ancient'],
        amountRange: [2, 4],
        creditRange: [0, 0],
        xpRange: [60, 140],
        reputationGain: [12, 24],
        questTypes: ['daily'],
        nameRu: 'Древние образцы',
        nameEn: 'Ancient specimens',
        descRu: 'Лабораторный запрос на древних сущностей',
        descEn: 'Lab request for ancient entities',
      },

      // ── Void Seekers (relic item + rift) ──────────────────────────────────
      // Deliver relic item — daily
      {
        id: 'vs_deliver_relic_exotic_d',
        faction: 'void_seekers',
        type: 'deliver_object',
        targetType: 'relic',
        targetRarities: ['exotic'],
        amountRange: [4, 8],
        creditRange: [0, 0],
        xpRange: [45, 110],
        reputationGain: [10, 22],
        questTypes: ['daily'],
        nameRu: 'Реликвии пустоты',
        nameEn: 'Void relics',
        descRu: 'Пустотникам нужны реликвии для расшифровки',
        descEn: 'Void Seekers need relics for deciphering',
      },
      {
        id: 'vs_deliver_relic_ancient_d',
        faction: 'void_seekers',
        type: 'deliver_object',
        targetType: 'relic',
        targetRarities: ['ancient'],
        amountRange: [1, 3],
        creditRange: [0, 0],
        xpRange: [85, 210],
        reputationGain: [20, 38],
        questTypes: ['daily'],
        nameRu: 'Древняя реликвия',
        nameEn: 'Ancient relic',
        descRu: 'Требуется для дешифровки протоколов пустоты',
        descEn: 'Required for deciphering void protocols',
      },
      // Deliver relic item — weekly
      {
        id: 'vs_deliver_relic_ancient_w',
        faction: 'void_seekers',
        type: 'deliver_object',
        targetType: 'relic',
        targetRarities: ['ancient'],
        amountRange: [7, 14],
        creditRange: [0, 0],
        xpRange: [210, 540],
        reputationGain: [34, 62],
        questTypes: ['weekly'],
        nameRu: 'Массовая поставка реликвий',
        nameEn: 'Mass relic delivery',
        descRu: 'Крупный заказ для исследовательского корпуса',
        descEn: 'Bulk order for the research corps',
      },
      {
        id: 'vs_deliver_relic_relic_w',
        faction: 'void_seekers',
        type: 'deliver_object',
        targetType: 'relic',
        targetRarities: ['relic'],
        amountRange: [2, 5],
        creditRange: [0, 0],
        xpRange: [370, 780],
        reputationGain: [46, 78],
        questTypes: ['weekly'],
        nameRu: 'Реликтовые артефакты',
        nameEn: 'Relic artifacts',
        descRu: 'Исключительная ценность для архивов Пустотников',
        descEn: 'Exceptional value for the Void Seekers\' archives',
      },
      {
        id: 'vs_deliver_relic_hybrid_w',
        faction: 'void_seekers',
        type: 'deliver_object',
        targetType: 'relic',
        targetRarities: ['hybrid'],
        amountRange: [1, 1],
        creditRange: [0, 0],
        xpRange: [580, 920],
        reputationGain: [58, 92],
        questTypes: ['weekly'],
        nameRu: 'Гибридный артефакт',
        nameEn: 'Hybrid artifact',
        descRu: 'Реликт до-пустотной эпохи',
        descEn: 'A relic from the pre-void era',
      },
      // Find rift — daily
      {
        id: 'vs_find_rift_exotic_d',
        faction: 'void_seekers',
        type: 'find_object',
        targetType: 'rift',
        targetRarities: ['exotic'],
        amountRange: [5, 10],
        creditRange: [0, 0],
        xpRange: [30, 75],
        reputationGain: [8, 16],
        questTypes: ['daily'],
        nameRu: 'Картографирование разломов',
        nameEn: 'Rift mapping',
        descRu: 'Обнаружьте разломы для технического анализа',
        descEn: 'Discover rifts for technical analysis',
      },
      {
        id: 'vs_find_rift_ancient_d',
        faction: 'void_seekers',
        type: 'find_object',
        targetType: 'rift',
        targetRarities: ['ancient'],
        amountRange: [2, 5],
        creditRange: [0, 0],
        xpRange: [65, 165],
        reputationGain: [14, 30],
        questTypes: ['daily'],
        nameRu: 'Ценные разломы',
        nameEn: 'Valuable rifts',
        descRu: 'Фрагменты пространства-времени',
        descEn: 'Fragments of spacetime',
      },
      // Find rift — weekly
      {
        id: 'vs_find_rift_ancient_w',
        faction: 'void_seekers',
        type: 'find_object',
        targetType: 'rift',
        targetRarities: ['ancient'],
        amountRange: [9, 18],
        creditRange: [0, 0],
        xpRange: [190, 460],
        reputationGain: [32, 58],
        questTypes: ['weekly'],
        nameRu: 'Сканирование разломов',
        nameEn: 'Rift scan',
        descRu: 'Масштабная экспедиция по сбору пространственных данных',
        descEn: 'Large-scale expedition for spatial data collection',
      },
      {
        id: 'vs_find_rift_relic_w',
        faction: 'void_seekers',
        type: 'find_object',
        targetType: 'rift',
        targetRarities: ['relic'],
        amountRange: [2, 5],
        creditRange: [0, 0],
        xpRange: [290, 660],
        reputationGain: [40, 72],
        questTypes: ['weekly'],
        nameRu: 'Реликтовые разломы',
        nameEn: 'Relic rifts',
        descRu: 'Реликты пространств-времени ушедших эпох',
        descEn: 'Spacetime relics from lost eras',
      },
      // Sell relic item — daily
      {
        id: 'vs_sell_relic_exotic_d',
        faction: 'void_seekers',
        type: 'sell_object',
        targetType: 'relic',
        targetRarities: ['exotic'],
        amountRange: [5, 10],
        creditRange: [0, 0],
        xpRange: [30, 80],
        reputationGain: [6, 14],
        questTypes: ['daily'],
        nameRu: 'Продать реликвии',
        nameEn: 'Sell relics',
        descRu: 'Передайте реликвии на рынок — Пустотники доплатят',
        descEn: 'Sell relics on the market — Void Seekers will pay extra',
      },
      {
        id: 'vs_sell_relic_ancient_d',
        faction: 'void_seekers',
        type: 'sell_object',
        targetType: 'relic',
        targetRarities: ['ancient'],
        amountRange: [2, 4],
        creditRange: [0, 0],
        xpRange: [65, 150],
        reputationGain: [12, 26],
        questTypes: ['daily'],
        nameRu: 'Древние реликвии',
        nameEn: 'Ancient relics',
        descRu: 'Пустотники выкупают древние технологические реликвии',
        descEn: 'Void Seekers buy ancient technological relics',
      },

      // ── Resonators (expeditions + asteroid + any) ─────────────────────────
      // Expeditions — daily
      {
        id: 'res_expeditions_daily_sm',
        faction: 'resonators',
        type: 'expeditions',
        targetType: null,
        targetRarities: [],
        amountRange: [5, 8],
        creditRange: [0, 0],
        xpRange: [80, 180],
        reputationGain: [12, 22],
        questTypes: ['daily'],
        nameRu: 'Резонансный патруль',
        nameEn: 'Resonance patrol',
        descRu: 'Резонаторы отправляют вас в разведывательные вылазки',
        descEn: 'Resonators send you on recon sorties',
      },
      {
        id: 'res_expeditions_daily_lg',
        faction: 'resonators',
        type: 'expeditions',
        targetType: null,
        targetRarities: [],
        amountRange: [9, 14],
        creditRange: [0, 0],
        xpRange: [140, 300],
        reputationGain: [18, 32],
        questTypes: ['daily'],
        nameRu: 'Расширенный патруль',
        nameEn: 'Extended patrol',
        descRu: 'Широкий охват для картографирования резонансных зон',
        descEn: 'Wide coverage for resonance zone mapping',
      },
      // Expeditions — repeatable
      {
        id: 'res_expeditions_repeatable',
        faction: 'resonators',
        type: 'expeditions',
        targetType: null,
        targetRarities: [],
        amountRange: [5, 10],
        creditRange: [0, 0],
        xpRange: [60, 140],
        reputationGain: [8, 18],
        questTypes: ['repeatable'],
        nameRu: 'Постоянный мониторинг',
        nameEn: 'Continuous monitoring',
        descRu: 'Непрерывный мониторинг секторов для Резонаторов',
        descEn: 'Continuous sector monitoring for the Resonators',
      },
      // Expeditions — weekly
      {
        id: 'res_expeditions_weekly_sm',
        faction: 'resonators',
        type: 'expeditions',
        targetType: null,
        targetRarities: [],
        amountRange: [50, 70],
        creditRange: [0, 0],
        xpRange: [400, 800],
        reputationGain: [40, 68],
        questTypes: ['weekly'],
        nameRu: 'Серия экспедиций',
        nameEn: 'Expedition series',
        descRu: 'Масштабная разведка для Резонаторов',
        descEn: 'Large-scale recon for the Resonators',
      },
      {
        id: 'res_expeditions_weekly_lg',
        faction: 'resonators',
        type: 'expeditions',
        targetType: null,
        targetRarities: [],
        amountRange: [80, 120],
        creditRange: [0, 0],
        xpRange: [600, 1100],
        reputationGain: [52, 84],
        questTypes: ['weekly'],
        nameRu: 'Большая разведка',
        nameEn: 'Grand recon',
        descRu: 'Полноценная картографическая операция',
        descEn: 'Full-scale cartographic operation',
      },
      // Find any U2 item — daily
      {
        id: 'res_find_any_exotic_d',
        faction: 'resonators',
        type: 'find_object',
        targetType: null,
        targetRarities: ['exotic'],
        amountRange: [5, 10],
        creditRange: [0, 0],
        xpRange: [35, 85],
        reputationGain: [8, 15],
        questTypes: ['daily'],
        nameRu: 'Сбор находок',
        nameEn: 'Collect finds',
        descRu: 'Обнаружьте объекты в секторах U2',
        descEn: 'Discover objects in U2 sectors',
      },
      {
        id: 'res_find_any_ancient_d',
        faction: 'resonators',
        type: 'find_object',
        targetType: null,
        targetRarities: ['ancient'],
        amountRange: [2, 4],
        creditRange: [0, 0],
        xpRange: [70, 170],
        reputationGain: [14, 28],
        questTypes: ['daily'],
        nameRu: 'Древние находки',
        nameEn: 'Ancient finds',
        descRu: 'Зафиксируйте древние объекты в экспедициях',
        descEn: 'Record ancient objects during expeditions',
      },
      // Find any U2 item — weekly
      {
        id: 'res_find_any_ancient_w',
        faction: 'resonators',
        type: 'find_object',
        targetType: null,
        targetRarities: ['ancient'],
        amountRange: [8, 16],
        creditRange: [0, 0],
        xpRange: [200, 480],
        reputationGain: [32, 60],
        questTypes: ['weekly'],
        nameRu: 'Исследование секторов',
        nameEn: 'Sector research',
        descRu: 'Систематическое изучение аномалий и объектов U2',
        descEn: 'Systematic study of U2 anomalies and objects',
      },
      {
        id: 'res_find_any_relic_w',
        faction: 'resonators',
        type: 'find_object',
        targetType: null,
        targetRarities: ['relic'],
        amountRange: [2, 5],
        creditRange: [0, 0],
        xpRange: [300, 680],
        reputationGain: [42, 74],
        questTypes: ['weekly'],
        nameRu: 'Ценные открытия',
        nameEn: 'Valuable discoveries',
        descRu: 'Реликтовые находки для базы данных Резонаторов',
        descEn: 'Relic finds for the Resonators\' database',
      },
      // Deliver asteroid — daily (unique to Resonators)
      {
        id: 'res_deliver_asteroid_exotic_d',
        faction: 'resonators',
        type: 'deliver_object',
        targetType: 'asteroid',
        targetRarities: ['exotic'],
        amountRange: [4, 8],
        creditRange: [0, 0],
        xpRange: [35, 90],
        reputationGain: [9, 18],
        questTypes: ['daily'],
        nameRu: 'Астероидная руда',
        nameEn: 'Asteroid ore',
        descRu: 'Добудьте и доставьте астероиды для резонансного синтеза',
        descEn: 'Mine and deliver asteroids for resonance synthesis',
      },
      {
        id: 'res_deliver_asteroid_ancient_d',
        faction: 'resonators',
        type: 'deliver_object',
        targetType: 'asteroid',
        targetRarities: ['ancient'],
        amountRange: [1, 3],
        creditRange: [0, 0],
        xpRange: [75, 190],
        reputationGain: [17, 33],
        questTypes: ['daily'],
        nameRu: 'Древняя руда',
        nameEn: 'Ancient ore',
        descRu: 'Астероиды древней эпохи для особых реакций',
        descEn: 'Ancient-era asteroids for special reactions',
      },

      // ── Haulers (cross-universe: deliver U1 items for crystals) ───────────
      {
        id: 'haul_deliver_creature_d',
        faction: 'haulers',
        type: 'deliver_object',
        targetType: 'creature',
        targetRarities: ['common', 'rare'],
        amountRange: [2, 5],
        creditRange: [0, 0],
        xpRange: [50, 120],
        reputationGain: [10, 22],
        questTypes: ['daily'],
        nameRu: 'Живой груз',
        nameEn: 'Live cargo',
        descRu: 'Дальнобойщики принимают существ из U1 — нарасхват',
        descEn: 'Haulers accept U1 creatures — high demand',
      },
      {
        id: 'haul_deliver_artifact_d',
        faction: 'haulers',
        type: 'deliver_object',
        targetType: 'artifact',
        targetRarities: ['common', 'rare'],
        amountRange: [2, 5],
        creditRange: [0, 0],
        xpRange: [55, 130],
        reputationGain: [11, 24],
        questTypes: ['daily'],
        nameRu: 'Ценный груз',
        nameEn: 'Valuable cargo',
        descRu: 'Артефакты из U1 ценятся здесь вдвойне',
        descEn: 'U1 artifacts are doubly valued here',
      },
      {
        id: 'haul_deliver_creature_w',
        faction: 'haulers',
        type: 'deliver_object',
        targetType: 'creature',
        targetRarities: ['rare'],
        amountRange: [6, 12],
        creditRange: [0, 0],
        xpRange: [180, 440],
        reputationGain: [28, 54],
        questTypes: ['weekly'],
        nameRu: 'Крупная партия существ',
        nameEn: 'Large creature shipment',
        descRu: 'Еженедельная поставка редких существ из первой вселенной',
        descEn: 'Weekly shipment of rare creatures from the first universe',
      },
      {
        id: 'haul_deliver_artifact_w',
        faction: 'haulers',
        type: 'deliver_object',
        targetType: 'artifact',
        targetRarities: ['rare'],
        amountRange: [6, 12],
        creditRange: [0, 0],
        xpRange: [190, 460],
        reputationGain: [30, 56],
        questTypes: ['weekly'],
        nameRu: 'Крупная партия артефактов',
        nameEn: 'Large artifact shipment',
        descRu: 'Еженедельная поставка редких артефактов из U1',
        descEn: 'Weekly shipment of rare artifacts from U1',
      },
      {
        id: 'haul_deliver_creature_epic_w',
        faction: 'haulers',
        type: 'deliver_object',
        targetType: 'creature',
        targetRarities: ['epic'],
        amountRange: [1, 2],
        creditRange: [0, 0],
        xpRange: [320, 680],
        reputationGain: [38, 68],
        questTypes: ['weekly'],
        nameRu: 'Элитный груз',
        nameEn: 'Elite cargo',
        descRu: 'Эпические существа стоят целое состояние в другой вселенной',
        descEn: 'Epic creatures are worth a fortune in another universe',
        reputationRequirements: [{ factionId: 'haulers', operator: '>=', value: 100 }],
        reputationPenalties: [{ factionId: 'bioengineers', amount: 8 }],
      },
      {
        id: 'haul_deliver_artifact_epic_w',
        faction: 'haulers',
        type: 'deliver_object',
        targetType: 'artifact',
        targetRarities: ['epic'],
        amountRange: [1, 2],
        creditRange: [0, 0],
        xpRange: [330, 700],
        reputationGain: [40, 72],
        questTypes: ['weekly'],
        nameRu: 'Ценный контрабанд',
        nameEn: 'Valuable contraband',
        descRu: 'Эпические артефакты — дефицитный товар в U2',
        descEn: 'Epic artifacts are scarce goods in U2',
        reputationRequirements: [{ factionId: 'haulers', operator: '>=', value: 100 }],
        reputationPenalties: [{ factionId: 'tech_institute', amount: 8 }],
      },
      {
        id: 'haul_deliver_legendary_w',
        faction: 'haulers',
        type: 'deliver_object',
        targetType: 'creature',
        targetRarities: ['legendary'],
        amountRange: [1, 1],
        creditRange: [0, 0],
        xpRange: [500, 860],
        reputationGain: [52, 86],
        questTypes: ['weekly'],
        nameRu: 'Легендарный контракт',
        nameEn: 'Legendary contract',
        descRu: 'Только избранные везут такой груз между вселенными',
        descEn: 'Only the trusted transport such cargo between universes',
        reputationRequirements: [{ factionId: 'haulers', operator: '>=', value: 200 }],
        reputationPenalties: [{ factionId: 'bioengineers', amount: 15 }, { factionId: 'tech_institute', amount: 10 }],
      },
    ],

    // Item rewards from special quests (low chance)
    itemRewards: [
      { id: 'bioscanner', nameRu: 'Биосканер',    nameEn: 'Bioscanner',     effect: 'creature_chance', value: 5, icon: '🔬', chance: 0.07 },
      { id: 'astromap',   nameRu: 'Астрокарта',    nameEn: 'Astro Map',      effect: 'anomaly_chance',  value: 5, icon: '🗺️', chance: 0.07 },
      { id: 'lucky_coin', nameRu: 'Монета удачи',  nameEn: 'Lucky Coin',     effect: 'rarity_boost',    value: 3, icon: '🪙', chance: 0.05 },
    ],
    itemCompensationCredits: 2000, // credits if player already has the item

    // Smuggler NPC (Black Market credit→star exchange)
    smuggler: {
      creditsPerStar: 100000,
      maxStarsPerWeek: 5,
      minReputation: 250,       // Black Market reputation required
      factionId: 'black_market',
    },
  },
  // ─── BLITZ RAID ────────────────────────────────────────────────────────────
  blitz: {
    cooldownHours:         6,     // cooldown after each session
    cooldownReducerFactor: 0.75,  // factor when blitz_cooldown_reducer buff is active
    stabilizerSwipes:      5,     // guaranteed safe swipes per session with stabilizer
    baseExplosionChance:   0.04,  // risk on 1st swipe (4%)
    explosionIncrement:    0.065, // multiplied by n^power per accumulated card
    explosionPower:        1.15,  // curve steepness
    maxExplosionChance:    0.88,  // hard cap
    rewardMultiplier:      0.4,   // blitz credits = normal × rewardMultiplier
    xpMultiplier:          0.5,   // blitz XP = normal × xpMultiplier
  },

  // ─── SECOND UNIVERSE (U2) ──────────────────────────────────────────────────
  universe2: {
    travelDurationHours: 6,        // time to travel between universes
    crossUniverseSellBonus: 1.5,   // 1.5× sell price for items from the other universe

    // U2-only rarity scale (5 tiers)
    // Weights tuned to proportional distribution matching U1 (not overweighting rare tiers)
    rarity: {
      exotic:      { weight: 72.0, xpMultiplier: 1.5,   priceMultiplier: 1.2,   label: 'Экзотический',  tier: 1 },
      ancient:     { weight: 23.0,  xpMultiplier: 4.0,   priceMultiplier: 2.4,   label: 'Древний',       tier: 2 },
      relic:       { weight: 4.2,  xpMultiplier: 9.0,   priceMultiplier: 4.8,   label: 'Реликтовый',    tier: 3 },
      hybrid:      { weight: 0.74,  xpMultiplier: 20.0,  priceMultiplier: 9.6,   label: 'Гибридный',     tier: 4 },
      singularity: { weight: 0.06,  xpMultiplier: 50.0,  priceMultiplier: 24.0,  label: 'Сингулярность', tier: 5 },
    },

    // Currency: crystals
    currency: 'crystals',

    // U2 find types
    findTypes: {
      echo:       { weight: 35, label: 'Эхо (обломки)' },
      relic:      { weight: 25, label: 'Реликвия (артефакт)' },
      entity:     { weight: 20, label: 'Сущность (существо)' },
      rift:       { weight: 15, label: 'Разлом (аномалия)' },
      asteroid:   { weight: 5,  label: 'Астероид' },
    },

    // U2 asteroid resources by U2 rarity (same template counts as U1: 3/2/2/1/1)
    // Tuned to be roughly x1.20 of corresponding U1 rarity tier economics.
    asteroidResources: {
      exotic: [
        { id: 'void_iron',     name: 'Пустотное железо',      pricePerTon: 5  },
        { id: 'phase_nickel',  name: 'Фазовый никель',        pricePerTon: 7  },
        { id: 'echo_silicate', name: 'Эхо-силикаты',          pricePerTon: 10 },
      ],
      ancient: [
        { id: 'chrono_titan',  name: 'Хроно-титан',           pricePerTon: 17 },
        { id: 'rift_cobalt',   name: 'Разломный кобальт',     pricePerTon: 19 },
      ],
      relic: [
        { id: 'aether_earth',  name: 'Эфирные редкоземы',     pricePerTon: 34 },
        { id: 'prism_iridium', name: 'Призматический иридий', pricePerTon: 43 },
      ],
      hybrid: [
        { id: 'living_platinum', name: 'Живая платина',       pricePerTon: 96 },
      ],
      singularity: [
        { id: 'omega_flux',    name: 'Омега-флюкс',           pricePerTon: 360 },
      ],
    },

    // U2 zones
    zones: [
      {
        id: 'u2_shattered_void',
        name: 'Расколотая пустота',
        nameEn: 'Shattered Void',
        minLevel: 1,
        universe: 2,
        rarityMultiplier: 1.0,
        findTypeModifiers: { echo: 1.5, relic: 1.0, entity: 0.8, rift: 0.6 },
        creditMultiplier: 1.0,
        xpMultiplier: 1.0,
      },
      {
        id: 'u2_crystal_nebula',
        name: 'Кристальная туманность',
        nameEn: 'Crystal Nebula',
        minLevel: 15,
        universe: 2,
        rarityMultiplier: 1.3,
        findTypeModifiers: { echo: 1.0, relic: 1.5, entity: 1.2, rift: 0.8, asteroid: 1.5 },
        creditMultiplier: 1.3,
        xpMultiplier: 1.25,
      },
      {
        id: 'u2_temporal_rift',
        name: 'Временной разлом',
        nameEn: 'Temporal Rift',
        minLevel: 20,
        universe: 2,
        rarityMultiplier: 1.6,
        findTypeModifiers: { rift: 3.0, relic: 1.5, entity: 1.3, echo: 0.8 },
        creditMultiplier: 1.6,
        xpMultiplier: 1.5,
      },
      {
        id: 'u2_ancient_core',
        name: 'Древнее ядро',
        nameEn: 'Ancient Core',
        minLevel: 25,
        universe: 2,
        rarityMultiplier: 2.0,
        findTypeModifiers: { relic: 2.5, entity: 1.5, rift: 1.5, echo: 0.5 },
        creditMultiplier: 2.0,
        xpMultiplier: 1.8,
      },
      {
        id: 'u2_singularity_edge',
        name: 'Грань сингулярности',
        nameEn: 'Singularity Edge',
        minLevel: 30,
        universe: 2,
        rarityMultiplier: 2.5,
        findTypeModifiers: { rift: 2.5, entity: 2.0, relic: 2.0, echo: 0.5, asteroid: 0.3 },
        creditMultiplier: 2.5,
        xpMultiplier: 2.2,
      },
    ],

    // U2 economy
    economy: {
      baseXP: { echo: 20, relic: 35, entity: 28, rift: 40, asteroid: 15 },
    },

    // Sectors for U2
    sectors: ['ΩRA', 'ΔXI', 'ΣPH', 'ΨON', 'ΦER', 'ΛUM', 'ΘRX', 'ΞKA'],
  },
};

module.exports = gameConfig;
